### ISSUE TITLE
requiring "assert" in index.js but it's not listed as a dependency 

### ISSUE THREAD

**Issue by suark** [cosmosio/get-closest#3]
React-Native 0.42
@turf/turf": ^3.11.2

I am using these libraries and your package gets installed. I see in the package.json of "get_closest", that it was required by "/@turf/dissolve".

I am getting an error that I do not have the module "assert" and I was able to track it down as being required in your index.js ( https://github.com/cosmosio/get-closest/blob/master/index.js#L10 )

I believe this indicates that your project is not indicating this dependency. For now I have to manually install the package.

**Comment by podefr** [comment]
Hi, thanks a lot for raising this issue. I see that there's already a PR addressing it.
I'll spend a bit more time assessing if we still want to use assert or replace it with a ad-hoc function since assert is a pretty heavy dependency, and I'll get back to you

**Comment by suark** [comment]
Hi, @podefr 

I just wanted to post this to cross link the issues https://github.com/Turfjs/turf/issues/600

**Comment by podefr** [comment]
thanks @suark, I removed the dependency on assert (replaced with a simple throw statement) and pushed version 0.0.4, which should solve your issue. thanks a lot for reporting it!

**Comment by suark** [comment]
@podefr thank you!
